version: "3.3"

services:
  react:
    build: ./react-app
    container_name: React
    ports:
      - "3000:3000"
    depends_on:
      - dotnet
    environment:
      - BACKEND_IP=54.91.145.197
  dotnet:
    build: ./asp.net
    container_name: DotNet
    ports:
      - "5000:80"  
    depends_on:
      - mysql

  mysql:
    image: pradeep34946/mysql:v1
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password